<?php
       /* This File Generated By Beshoy Gamal*/

// Home > Church
Breadcrumbs::for('churches', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الكنائس', route('admin.churches'));
});
// Home > Church > Create
Breadcrumbs::for('create_church', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الكنائس', route('admin.churches'));
    $trail->push('إضافة كنيسة', route('admin.churches.create'));
});
// Home > Church > Edit
Breadcrumbs::for('edit_church', function ($trail, $church) {
    $trail->parent('home');
    $trail->push('قائمة الكنائس', route('admin.churches'));
    $trail->push($church->name, route('admin.churches.edit', $church->id));
});
