<?php
/* This File Generated By Beshoy Gamal*/

###### Admin Section #####
// Home > SubAreas
Breadcrumbs::for('subAreas', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة المناطق', route('admin.subAreas'));
});
// Home > SubAreas > Create
Breadcrumbs::for('create_subArea', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة المناطق', route('admin.subAreas'));
    $trail->push('إضافة منطقة جديدة', route('admin.subAreas.create'));
});
// Home > SubAreas > Edit
Breadcrumbs::for('edit_subArea', function ($trail, $subArea) {
    $trail->parent('home');
    $trail->push('قائمة المناطق', route('admin.subAreas'));
    $trail->push($subArea->name, route('admin.subAreas.edit', $subArea->id));
});
####### Frontend #########

