<?php

/**
 *  This File Generated By Beshoy Gamal
 *
 **/

// Home
/*Breadcrumbs::for('home', function ($trail) {
    $trail->push(__('admin/sidebar.dashboard'), route('admin.dashboard'));
});
Breadcrumbs::for('edit_profile', function ($trail, $admin) {
    $trail->parent('home');
    $trail->push($admin->name, route('admin.edit.profile', $admin->id));
});*/
