<?php
/* This File Generated By Beshoy Gamal*/

###### Admin Section #####

// Home > Cities
Breadcrumbs::for('cities', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.cities'), route('cities'));
});
// Home > Cities > Create
Breadcrumbs::for('create_city', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.cities'), route('cities'));
    $trail->push(__('admin/sidebar.add.city'), route('cities.create'));
});
// Home > Cities > Edit
Breadcrumbs::for('edit_city', function ($trail, $city) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.cities'), route('cities'));
    $trail->push($city->name, route('cities.edit', $city->id));
});
####### Frontend #########

