<?php
/* This File Generated By Beshoy Gamal*/

###### Admin Section #####

// Home > Safes
Breadcrumbs::for('safes', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.safes'), route('safes'));
});
// Home > Safes > Create
Breadcrumbs::for('create_safe', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.safes'), route('safes'));
    $trail->push(__('admin/sidebar.add.safe'), route('safes.create'));
});
// Home > Safes > Edit
Breadcrumbs::for('edit_safe', function ($trail, $safe) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.safes'), route('safes'));
    $trail->push($safe->name, route('safes.edit', $safe->id));
});
####### Frontend #########

