<?php
/* This File Generated By Beshoy Gamal*/
###### Admin Section #####
// Home > Areas
Breadcrumbs::for('areas', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.areas'), route('areas'));
});
// Home > Areas > Create
Breadcrumbs::for('create_area', function ($trail) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.areas'), route('areas'));
    $trail->push(__('admin/sidebar.add.area'), route('areas.create'));
});
// Home > Areas > Edit
Breadcrumbs::for('edit_area', function ($trail, $area) {
    $trail->parent('home');
    $trail->push(__('admin/sidebar.areas'), route('areas'));
    $trail->push($area->name, route('areas.edit', $area->id));
});
####### Frontend #########

