<?php

    $dir = base_path('Modules/');
    $files = scandir($dir);
    foreach ($files as $file) {
        if (!is_dir($file)) {
            $path = base_path("Modules/" . $file . "/Routes/breadcrumbs.php");
            if (file_exists($path)) {
                File::getRequire($path);

            } else {
               // $content= '<br/> /* This File Generated By Beshoy Gamal*/';
                file_put_contents($path,'');
            }
        }
    }
Breadcrumbs::for('home', function ($trail) {
    $trail->push('الرئيسية', route('dashboard'));
});
