<?php
/* This File Generated By Beshoy Gamal*/
###### Admin Section #####
// Home > Countries
Breadcrumbs::for('countries', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الدول', route('countries'));
});
// Home > Countries > Create
Breadcrumbs::for('create_country', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الدول', route('countries'));
    $trail->push('إضافة دولة', route('countries.create'));
});
// Home > Countries > Edit
Breadcrumbs::for('edit_country', function ($trail, $country) {
    $trail->parent('home');
    $trail->push('قائمة الدول', route('countries'));
    $trail->push($country->name, route('countries.edit', $country->id));
});
####### Frontend #########

