<?php
/* This File Generated By Beshoy Gamal */


// Home > Employees
Breadcrumbs::for('employees', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الموظفين', route('employees'));
});
// Home > Employees > Create
Breadcrumbs::for('create_employee', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة الموظفين', route('employees'));
    $trail->push('إضافة موظف جديد', route('employees.create'));
});
// Home > Employees > Edit
Breadcrumbs::for('edit_employee', function ($trail, $employee) {
    $trail->parent('home');
    $trail->push('قائمة الموظفين', route('employees'));
    $trail->push($employee->name, route('employees.edit', $employee->id));
});

