<?php
/* This File Generated By Beshoy Gamal */


// Home > expensives
Breadcrumbs::for('expensives', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة تصنيف المصروفات', route('expensives'));
});
// Home > expensives > Create
Breadcrumbs::for('create_expensive', function ($trail) {
    $trail->parent('home');
    $trail->push('قائمة تصنيف المصروفات', route('expensives'));
    $trail->push('إضافة تصنيف مصروف جديد', route('expensives.create'));
});
// Home > expensives > Edit
Breadcrumbs::for('edit_expensive', function ($trail, $expensive) {
    $trail->parent('home');
    $trail->push('قائمة تصنيف المصروفات', route('expensives'));
    $trail->push($expensive->name, route('expensives.edit', $expensive->id));
});

